services:
  - type: web
    name: story-generator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: GOOGLE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false